# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9862d78fb806c4bb629f737de7a5cb8c76e6c840aa27c3c891ca817a1d882c9fb8adda5585fe12e34a90fa86812f1187434eb36bf3789295dfc14d0c2492ade
    facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
    facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
test:
  secret_key_base: 94bcf2fbdff8a0fb7498024975d194e2e023c0176afb7213338beac883e0817ba2a608313b5202abd578af80f2f94d9ba71c8740aefca280c38d6569ccc692d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
